spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reserva_facil_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

